training:
  epochs: 15
  batch_size: 32
  learning_rate: 1e-5

model:
  embedding_size: 256

loss:
  margin: 1.0

paths:
  train_csv: "pairs_train.csv"
  pretrained_model: "src/models/checkpoints/verifier_siamese.pt"
  save_model: "src/models/checkpoints/verifier_finetuned.pt"